Updated Devos nav to match CBA nav
UCF/CBA-Schools-Theme pull request #1
Opened 2017-07-11 19:10 UTC by rjucf

2017-07-11 19:28 UTC, cjg89 approved these changes

2017-07-11 19:33 UTC, cjg89 requested changes

2017-07-11 19:33 UTC, cjg89 commented on static/scss/_layout.scss
> +    @media (min-width: $screen-md-min) {
Sorry, I didn't catch this until just now--I think you need to update this media query to $screen-sm-min to prevent white text on dropdown items at the -sm breakpoint. See attached
![screen shot 2017-07-11 at 2 29 27 pm](https://user-images.githubusercontent.com/1649216/28086751-a586d96a-6645-11e7-82e1-e40aed1e2fa4.png)

2017-07-11 19:40 UTC, rjucf commented on static/scss/_layout.scss
> +    @media (min-width: $screen-md-min) {
Good Catch Jo: https://github.com/UCF/CBA-Schools-Theme/pull/1/commits/ae0fb04f912b7ac86ded9841c23fcae580b36e9b

2017-07-11 20:09 UTC, cjg89 approved these changes

2017-07-13 14:34 UTC, jmbarne3 approved these changes

2017-07-13 17:23 UTC, keeeeeegan approved these changes

2017-10-18 13:04 UTC, merged