Refactored file_get_contents to wp_remote_get
UCF/CBA-Schools-Theme pull request #8
Opened 2019-06-25 19:16 UTC by rjucf

Fixes #5

2019-06-25 20:06 UTC, jmbarne3 approved these changes

2019-06-26 13:37 UTC, cjg89 approved these changes

2019-06-26 15:37 UTC, cjg89 requested changes

2019-06-26 15:37 UTC, cjg89 commented on functions/feeds.php
>  			if ( is_wp_error( $content ) ) {
By adding `wp_remote_retrieve_body()`, `$content` will no longer ever be assigned a `WP_Error` object, so the `is_wp_error` check will need to be updated to check for an empty string (which `wp_remote_retrieve_body` returns if `wp_remote_get` returns an empty or invalid response)

2019-06-26 15:57 UTC, jmbarne3 approved these changes

2019-06-26 15:58 UTC, cjg89 approved these changes

2019-06-26 16:58 UTC, cadie approved these changes

2019-06-26 18:49 UTC, merged